name: memedex
root: ./
# This environment variable is used for neovim configuration 
# (this ensures that opening html file is for django template)
# See https://github.com/malkoG/dotfiles/blob/main/private_dot_config/nvim/after/ftplugin/html.lua
pre_window: export USING_DJANGO_TEMPLATE=yes 
windows:
  - editor:
      layout: main-vertical
      panes:
        - poetry shell
  - debugging:
      layout: main-vertical
      panes:
        - poetry run python manage.py runserver
        - poetry run python manage.py tailwind start
        - poetry run python manage.py shell

